  dev_api:
    container_name: dev_api
    image: nginx
    restart: always
    ports:
      - 3001:3001
    env_file:
      - .env-api

  dev_frontend:
    container_name: dev_frontend
    image: nginx
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env-frontend