version: '3.3'

services:
  dev_mysql:
    image: mysql:8.3
    container_name: dev_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00t2024
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123!J0yGr
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql

  dev_redis:
    container_name: dev_redis
    image: redis:6.2-alpine 
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "dev123!J0yGr"]
    environment:
      - REDIS_PASSWORD=dev123!J0yGr
    volumes: 
      - ./data/cache:/data
    ports:
      - '6379:6379'
